### ISSUE TITLE
Unblock Tor Exit Nodes

### ISSUE THREAD

**Issue by Xeoncross** [trick77/ipset-blacklist#14]
Traffic flowing from the Tor Exit Nodes is often to slow to cause any kind of DoS attack. It could only be used to attempt to break in.

However, Tor is an important part of allowing the restricted people in the world access  to content. Shouldn't the Tor list be disabled by default and only enabled if a site has a problem with it?

**Comment by trick77** [comment]
I personally don't want TOR traffic on any of my servers but feel free to uncomment the exit node list from the script for your own usage. A Slowloris or nKiller doesn't need a lot of bandwidth and could be easily executed through TOR. But on the other hand blocking TOR won't prevent such attacks... so in the end it's just a matter of personal preference.
