### ISSUE TITLE
not a issue, but thanks and what I've done

### ISSUE THREAD

**Issue by justLearning2** [trick77/ipset-blacklist#17]
sorry, I don't know gitHub etiquette, but wanted to say thanks and show what I've added.
please remove this posting if not appropriate.

added source of bogus ip ranges:
 "http://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt" # bogus / bad src address space we should never see: http://www.team-cymru.org/Services/Bogons/

change create/add ipset
 ipset create blacklist -exist hash:net hashsize 128 maxelem 1048575
 ipset create blacklist_tmp -exist hash:net hashsize 128 maxelem 1048575
 ipset flush blacklist_tmp

also added section for iptables here instead of firewall startup
 if ! iptables -C INPUT -m set --match-set blacklist src -j DROP 2>/dev/null; then iptables -A INPUT -m set --match-set blacklist src -j DROP; fi

mini report so cron job can send us update
 echo -n " ... count of ip/networks in the ipset blacklist: "; ipset list blacklist | wc -l
 echo " ... current iptables/ipset statistics as of $(date):\n"; iptables -L -vn

used 'custom' section to do a dwnload/unzip/install of listed_ip_30 from http://www.stopforumspam.com/downloads/ ... which I can share if appropriate.

**Comment by trick77** [comment]
Thanks! I'm gonna add the bogons even though I don't think there will be a lot of malicious traffic originating from those prefixes since they can easily be filtered on edge routers.
