### ISSUE TITLE
error retrieving a couple lists.

### ISSUE THREAD

**Issue by mgaulton** [trick77/ipset-blacklist#19]
Just looking for suggestions on why these might not be working.

Error: curl returned HTTP response code 301 for URL https://www.maxmind.com/en/anonymous_proxies
Error: curl returned HTTP response code 000 for URL https://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt

**Comment by trick77** [comment]
a) looks like you're using an old version
b) 000 usually shows up when your IP is temporarily banned

**Comment by trick77** [comment]
Btw: banning fullbogons may break your network

**Comment by mgaulton** [comment]
Roger. Thanks. I clued into the older version just after posting,
still getting the 000 though. I run every 4 hours, so i'm not sure why
i might be banned. :)

**Comment by mgaulton** [comment]
Derp, https invalid cert was giving me the 000, http seems to work. It's a single host home server, i have pretty tight restrictions on it. I also block countries outside Canada and US :)
