### ISSUE TITLE
set type not supported?

### ISSUE THREAD

**Issue by mgaulton** [trick77/ipset-blacklist#23]
I started getting this recently and looking at the code, i don't really see the issue. I looked into the generated restore file and the below is received from the very first line when the script tries to restore.

server5:~ # ipset create blacklist-tmp hash:net family inet  hashsize 128 maxelem 1048575
ipset v6.25.1: Kernel error received: set type not supported

**Comment by trick77** [comment]
What OS/version is this?

**Comment by mgaulton** [comment]
It was on opensuse 13.2 but when i reran today, it was working. colour me confused. I think it was a local kernal issue but not clear why.
