### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by Eddy2909** [trick77/ipset-blacklist#24]
Hi guys!
thanks for this awesome script :)

just tried out your script on a raspberry pi and got the following rule by running "iptables -L --line-numbers"

Chain INPUT (policy ACCEPT 209 packets, 22426 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src
etc etc etc

Is this the way the script is intended to work?
thanks!!

**Comment by gagomap** [comment]
Yes, it's working 
Did you install Ipset ? View more at this link:
https://github.com/bryanroscoe/ipset-blacklist/blob/master/installUbuntu14_04.sh

**Comment by Eddy2909** [comment]
great thanks! jap installed ipset. I'm running debian wheezy on my raspberry.

So did I get it right: on every connection, the ip address is checked in the blacklist via the iptables ruleset?

**Comment by gagomap** [comment]
Yes, you're right. "Iptables -I...." mean  all IPs wil be checked before any iptables rules executed

Check my scripts. I have include ipset in iptables hardening settings and it will update everyday and when system startup. 
https://github.com/gagomap/iptables-boilerplate
And my list:
https://github.com/gagomap/ipset-blacklist

**Comment by Eddy2909** [comment]
yeah - great idea with the "default" firewall rulesets.. I'm running a little discovery server for the syncthing project (https://github.com/syncthing/syncthing) - so I dont need to control so much opened ports or connections ;)

btw: whats the difference between your and trick77s update script except the blacklist sources?

**Comment by Eddy2909** [comment]
another question: what about fail2ban?
do these rules work with fail2ban / the rules complement and do not replace right?
I'm using those guys:
1    fail2ban-ssh-ddos  tcp  --  anywhere             anywhere             multiport dports ssh
2    fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dports ssh

thanks!

**Comment by gagomap** [comment]
Yes, they can work together. I don't see any conflict.
There is no big difference between me and trick77s update script . He created this awesome scripts :D I only add more blacklist sources for my purpose. But if you will block a huge IPs list like me, you must change hashsize and maxelem of the set to fit your list.

**Comment by Eddy2909** [comment]
didn't get what the hashsize is for.. what do you use? btw: does the script a duplicate-check?

**Comment by Eddy2909** [comment]
and I think line 7 need to be changed to:
IP_BLACKLIST_CUSTOM=/${IP_BLACKLIST_DIR}/ip-blacklist-custom.list # optional, for your personal nemeses (no typo, plural)

**Comment by Eddy2909** [comment]
for everyone:
if "ipset v6.12.1: Error in line 1: Set cannot be created: set with the same name already exists" occures, run "ipset list -n" and delete the sets "blacklist-tmp" and "blacklist" via "ipset x blacklist-tmp" and "ipset x blacklist"

**Comment by Eddy2909** [comment]
hint for everyone:
nano /etc/network/interfaces
post-up ipset restore < /etc/ipset-blacklist/ip-blacklist.restore
post-up iptables -I INPUT -m set --match-set blacklist src -j DROP
works fine for reloading ruleset :+1:

**Comment by gagomap** [comment]
Thanks, it works on my side.

**Comment by Eddy2909** [comment]
but does this work on openvz too?

**Comment by gagomap** [comment]
i never test on openvz. 
But from trick77:
"The ipset command doesn't work under OpenVZ. It works fine on dedicated and fully virtualized servers like KVM though."

**Comment by Eddy2909** [comment]
jap :( I know..

next question: how does HASHSIZE and MAXELEM work?
I would like to parse some more blacklists..
How do I need to change HASHSIZE and MAXELEM?

**Comment by Eddy2909** [comment]
fyi:

http://www.malwaredomainlist.com/hostslist/ip.txt
https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist
https://palevotracker.abuse.ch/blocklists.php?download=ipblocklist
http://wget-mirrors.uceprotect.net/rbldnsd-all/dnsbl-1.uceprotect.net.gz
http://feeds.dshield.org/block.txt
http://malc0de.com/bl/IP_Blacklist.txt
http://www.projecthoneypot.org/list_of_ips.php?t=s
http://www.projecthoneypot.org/list_of_ips.php?t=w
http://www.projecthoneypot.org/list_of_ips.php?t=d
(http://www.nothink.org/blacklist/blacklist_ssh_day.txt)
(http://www.nothink.org/blacklist/blacklist_ssh_week.txt)
http://www.nothink.org/blacklist/blacklist_ssh_all.txt
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset

**Comment by gagomap** [comment]
You need read ipset manpage: 
http://webcache.googleusercontent.com/search?q=cache:http://ipset.netfilter.org/ipset.man.html

You need to be carefully when add more blacklists, it's will eat your resources or affect your customers or even you. If you have a heavy list, change HASHSIZE to 131072 and  MAXELEM to 264144. Your VPS can be crash if you change to bigger number.
You need manually run updatescripts to see how many IP in your lists. Then you can change HASHSIZE and MAXELEM to fit it.
This update script only work with text page.

**Comment by Eddy2909** [comment]
@gagomap 
thanks much for you help and patience ;)

**Comment by Eddy2909** [comment]
need some more help:
listed some ip's in a custom blacklist which is included in the script.
so far it works fine: this ip is listed in the set after updating the rules in *.restore and the iptables rule is there too..
but my stats saying: there are connections from this ip..
![31 172 30 180](https://cloud.githubusercontent.com/assets/12877411/10709453/9ac5e574-7a2f-11e5-8856-1e149eaab3ac.JPG)

I'm a bit helpless :(

**Comment by trick77** [comment]
Please post the output of
iptables -L -vn

**Comment by Eddy2909** [comment]
Chain INPUT (policy ACCEPT 130K packets, 136M bytes)
 pkts bytes target     prot opt in     out     source               destination
 4186  287K fail2ban-ssh-ddos  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 2909
 4186  287K fail2ban-ssh  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 2909
  209 32468 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 88426 packets, 144M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain fail2ban-ssh (1 references)
 pkts bytes target     prot opt in     out     source               destination
 4186  287K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain fail2ban-ssh-ddos (1 references)
 pkts bytes target     prot opt in     out     source               destination
 4186  287K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

**Comment by trick77** [comment]
1. You probably want the blacklist in the pole position
2. http://shorewall.net/NetfilterOverview.html --> Depending on where stats are gathered, you will always see a banned src IP.

**Comment by Eddy2909** [comment]
but shouldn't be blacklisted ips blocked by the script no matter where the rule is?

**Comment by trick77** [comment]
What? Did you even read my comment?

**Comment by Eddy2909** [comment]
ah right. jap sorry.. you mean fail2ban is pushing its rule after the script one or before? actually I'm using a post-up entry in interfaces..

**Comment by trick77** [comment]
I think that darkstat gathers the stats in promiscuous mode before it reaches the INPUT chain. That's why I posted the link to the Netfilter flow diagram. So even if darkstat sees a banned IP, this doesn't mean that this IP has access to higher level services (like ssh) on the server. This should be easy to test but make sure you don't lock yourself out.

**Comment by Eddy2909** [comment]
just tested it on a raspberry pi - it seams that darkstats collects after the "chain". my rules on the raspberry looking as you said: blacklist rule before fail2ban rules.. would you be so kind to give me a hint how to push the scriptsrule the right way? ("up" instead of "post-up" did not work)
