### ISSUE TITLE
Warning: curl returned ....

### ISSUE THREAD

**Issue by Nendra** [trick77/ipset-blacklist#26]
Hey,

today I updated this nice blacklist script. Now I get this warning message:

Warning: curl returned HTTP response code 303 for URL http://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1

Is there a way to solve it?

**Comment by mgaulton** [comment]
@Nendra they've disabled access to it on their end and put up a login form. You just have to wait for them to reopen it again.

**Comment by Nendra** [comment]
Okay, them I will wait.
