### ISSUE TITLE
6th point on your readme.md

### ISSUE THREAD

**Issue by joeshua** [trick77/ipset-blacklist#29]
I am noob since trying to get this work since 4 months but i update and i yet get stuck on 6th point and later if you try and give example for a noob like me will server even a new comer thanks in advance

**Comment by trick77** [comment]
If you set FORCE=yes it will be taken care of automagically once you run the script.

**Comment by joeshua** [comment]
Well if you saying in ipset-blacklist.conf by default it is force=yes in your script but do not know what i am doing wrong i tried what was given on your website too but do not know what i am doing wrong this is what i am getting below 
but this is what i am getting on iptables -L -vn
Chain INPUT (policy ACCEPT 126K packets, 6310K bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set blacklist src

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain OUTPUT (policy ACCEPT 129K packets, 13M bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by trick77** [comment]
Check out this post:
http://bencane.com/2012/09/17/iptables-linux-firewall-rules-for-a-basic-web-server/

You need a REJECT policy for your INPUT chain but make sure not to lock yourself out of the server.
