### ISSUE TITLE
Wrong error message?

### ISSUE THREAD

**Issue by BenoitMartin2** [trick77/ipset-blacklist#32]
Hi,

I got errors I don't understand cause my setup is OK.

> Error: missing executables among: curl egrep grep ipset iptables sed sort wc

```
which curl egrep grep ipset iptables sed sort wc
/usr/bin/curl
/bin/egrep
/bin/grep
/sbin/ipset
/sbin/iptables
/bin/sed
/usr/bin/sort
/usr/bin/wc
```

Thanks

**Comment by trick77** [comment]
Can you post the output of:
which curl ; which egrep ; which grep ; which ipset ; which iptables ; which sed ; which sort ; which wc

**Comment by BenoitMartin2** [comment]
It should be the same as already posted, no?

```
which curl ; which egrep ; which grep ; which ipset ; which iptables ; which sed ; which sort ; which wc
/usr/bin/curl
/bin/egrep
/bin/grep
/sbin/ipset
/sbin/iptables
/bin/sed
/usr/bin/sort
/usr/bin/wc
```

**Comment by trick77** [comment]
Just to make sure. 

I have no idea why "which" in your case reports missing binaries. Doesn't make any sense at all.

**Comment by BenoitMartin2** [comment]
FYI its a ProxMox 4.x server. I don't understand neither this is why I asked here ^^

**Comment by marc64738** [comment]
May it be that this error happens, when you call the script via cron? Just execute the script on commandline manually. If this works without errors and the script called via cron drops the "missing executables"-error:
put this line into update-blacklist.sh  after the shebang-line (line 2):
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
It may be that the environment variables are not known when called via cron.

**Comment by trick77** [comment]
Thanks @NET73, I'm closing this issue.

**Comment by cnaslain** [comment]
I also have the same fake error on a CentOS; dunno why. All expected binaries locations are in the path. 

[root@xxx ~]# cat /etc/centos-release
CentOS release 6.8 (Final)

[root@xxx ~]# which curl egrep grep ipset iptables sed sort wc
/usr/bin/curl
/bin/egrep
/bin/grep
/usr/sbin/ipset
/sbin/iptables
/bin/sed
/bin/sort
/usr/bin/wc

[root@xxx ~]# env |grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

**Comment by Steve8291** [comment]
cnaslain does the error happen when you run the script from the command line or from a cron job?

**Comment by cnaslain** [comment]
Only from the cron job witch is ran by root.
[root@xxx ~]# crontab -l -u root
[...]
33 23 * * * /opt/ipset-blacklist/update-blacklist.sh /etc/ipset-blacklist/ipset-blacklist.conf

When loggd-in as root and running the script manually; no error is shown:
[root@xxx ~]# /opt/ipset-blacklist/update-blacklist.sh /etc/ipset-blacklist/ipset-blacklist.conf                                                     ...........
Number of blacklisted IP/networks found: 76955

**Comment by Steve8291** [comment]
If you add the following to your crontab you can find out if it has the same environmental variables as you do when logged in as root.
`*/1 * * * * env > /root/env.output`
Wait 1 min and check your /root folder or wherever you have it output to.
`cat /root/env.output`
I'm guessing that it will have different paths than you do as a root user.
If so then just add the following after the shebang in the script file like NET73 said above:
```
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by cnaslain** [comment]
You're right; the environment is very limited:
[root@xxx ~]# cat /root/env.output
SHELL=/bin/sh
USER=root
PATH=/usr/bin:/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root

I'm gonna hack the script to add the missing paths.
Thx

**Comment by johnestep** [comment]
Same issue here running via cron so this worked:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

So thanks @NET73
