### ISSUE TITLE
Cron will not run command

### ISSUE THREAD

**Issue by Steve8291** [trick77/ipset-blacklist#36]
I don't know if anyone else is having this issue but I can not get cron to run the script. I've tried from within /etc/cron.d/update-blacklist  as well as root crontab -e. Neither will execute the script but it works fine from the command line. I'm running on Ubuntu. Am I doing something wrong?

**Comment by Steve8291** [comment]
Solved my problem. I had to update the script with the proper paths for my environmental variables before it would work.

**Comment by NET73** [comment]
Maybe trick77 can add this information into the Readme? I had the same issue as reported here: https://github.com/trick77/ipset-blacklist/issues/32#issuecomment-221065299
This was a problem on all my ubuntu boxes.

**Comment by Steve8291** [comment]
I had to add:
PATH=/usr/bin:/sbin:/bin

Because ipset and iptables are both in /sbin on Ubuntu.
By default cron's PATH=/usr/bin:/bin
What finally tipped my off was the error line:
"Error: missing executables among: curl egrep grep ipset iptables sed sort wc"
Could possibly add a note there to check PATH. A note in the readme would be super helpful as well.

**Comment by trick77** [comment]
Done
