### ISSUE TITLE
Looping Do not know what I have done wrong 

### ISSUE THREAD

**Issue by joeshua** [trick77/ipset-blacklist#37]
sudo sh update-blacklist.sh
[sudo] password for hostname:
/usr/local/sbin/update-blacklist.sh: fork: Cannot allocate memory
/usr/local/sbin/update-blacklist.sh: fork: Cannot allocate memory
/usr/local/sbin/update-blacklist.sh: fork: Cannot allocate memory
/usr/local/sbin/update-blacklist.sh: line 62: 27624 Killed                  iptables -I INPUT "${IPTABLES_IPSET_RULE_NUMBER:-1}" -m set --match-set "$IPSET_BLACKLIST_NAME" src -j DROP
Error: while adding the --match-set ipset rule to iptables
..........ipset v6.12.1: No command specified: unknown argument -file
Try `ipset help' for more information.

Number of blacklisted IP/networks found: 37799
..........ipset v6.12.1: No command specified: unknown argument -file
Try `ipset help' for more information.

Number of blacklisted IP/networks found: 37799
..........ipset v6.12.1: No command specified: unknown argument -file
Try `ipset help' for more information.

Number of blacklisted IP/networks found: 37799
..........
**(Keeps on going in loop)**

 whereis update-blacklist.sh
update-blacklist: /usr/local/bin/update-blacklist.sh /usr/local/sbin/update-blacklist.sh

**free -m**
             total       used       free     shared    buffers     cached
Mem:   1002        210        792          0          1         11
-/+ buffers/cache:        198        804
Swap:            0          0          0

As shown in the last line to add the given MAXELEM=80000 in the  ipset-blacklist.conf file  adding that gives same error

**Comment by trick77** [comment]
Impossible to diagnose without more data, looks like an outdated or incompatible distro.

**Comment by joeshua** [comment]
Using debain 7 isit incompatible distro ?

**Comment by trick77** [comment]
The script works perfectly with Debian, it has to be something on your end causing this. In fact, I have been using it on a Debian server for months without any issues.
