### ISSUE TITLE
unknown argument -file

### ISSUE THREAD

**Issue by ddeenniiss** [trick77/ipset-blacklist#40]
I have this error when i start /usr/local/sbin/update-blacklist.sh

............ipset v6.12.1: No command specified: unknown argument -file

**Comment by trick77** [comment]
The ipset version you're using is outdated. You may have to recompile a newer version of ipset or update the Linux Distro, which is probably old as well.

**Comment by trick77** [comment]
Btw. ipset 6.12 ist from 2012.

**Comment by ddeenniiss** [comment]
Yes, it's the version of wheezy.

**Comment by averyjparker** [comment]
You could edit /usr/local/sbin/update-blacklist.sh around line 99/100 like this...

#ipset -file  "$IP_BLACKLIST_RESTORE" restore
ipset restore < "$IP_BLACKLIST_RESTORE"

I ran into this on two systems and have worked around the lack of -file in ipset's older version by just passing the restore data via stdin...  So around line 99/100 in the script you change:
ipset -file  "$IP_BLACKLIST_RESTORE" restore
to 
ipset restore < "$IP_BLACKLIST_RESTORE"
or comment the original line out as I did above.
