### ISSUE TITLE
ipset-blacklist and fail2ban

### ISSUE THREAD

**Issue by localguru** [trick77/ipset-blacklist#41]
Hi,

what's the best way of living ipset-blacklist and fail2ban together? I wrote a little init.d script and run that after fail2ban, so that ipset-blacklist rule is on position 1 in INPUT chain. This is fine at boot time. But when modifying fail2ban rules and restart/reload fail2ban, fail2ban pushes itself on position 1 in INPUT chain. I didn't find a the say fail2ban to insert rules in INPUT chain at position >= 2, after ipset-blacklist, so I have to remove and insert ipset-blacklist again after each fail2ban change. Any idea for a better way?

Ciao
Marcus

**Comment by localguru** [comment]
Hi,

got help on the fail2ban list. One can create .local files in action.d to overwrite .conf files. There I changed "<chain> -p"  to chain "<chain> 2 -p". Calling 

    ipset restore < /etc/ipset-blacklist/ip-blacklist.restore
    iptables -I INPUT 1 -m set --match-set blacklist src -j DROP

is done in /etc/ufw/before.init as I use ufw firewall. /etc/ufw/before.init has to be chmod 750 on Ubuntu.

Ciao and thanks for your work!
Marcus

**Comment by trick77** [comment]
That's great, thanks! Will add this to the documentation.
