### ISSUE TITLE
ipset -file option

### ISSUE THREAD

**Issue by localguru** [trick77/ipset-blacklist#42]
Hi,

on systems with older ipset versions, like Ubuntu 12.04 LTS, the option -file is missing and update-blacklist.sh fails in line

  ipset -file  "$IP_BLACKLIST_RESTORE" restore

Why not changing to

  ipset restore < /etc/ipset-blacklist/ip-blacklist.restore

to be compatible with older ipset version?

Ciao!

**Comment by davidhrbac** [comment]
+1 Redhat/CentOS has the same issue...

**Comment by trick77** [comment]
Sorry, I'm not going to make it compatible for outdated ipset versions.
