### ISSUE TITLE
I don't understand "However, the blacklist won't do anything if the default policy of iptable's INPUT chain is set to ACCEPT."

### ISSUE THREAD

**Issue by jonisc** [trick77/ipset-blacklist#43]
Sorry but I'm really new to Linux network/ ipset/ iptables. 
Do I have to change something and how?

sudo iptables -t filter -L

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-vpnserver-tcp  tcp  --  anywhere             anywhere            
f2b-vpnserver-udp  udp  --  anywhere             anywhere            
f2b-nextcloud  tcp  --  anywhere             anywhere             multiport dports http,https
f2b-asterisk-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls
f2b-asterisk-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls
f2b-apache-modsecurity  tcp  --  anywhere             anywhere             multiport dports http,https
f2b-apache-overflows  tcp  --  anywhere             anywhere             multiport dports http,https
f2b-apache-noscript  tcp  --  anywhere             anywhere             multiport dports http,https
f2b-apache  tcp  --  anywhere             anywhere             multiport dports http,https
f2b-ssh-ddos  tcp  --  anywhere             anywhere             multiport dports ssh
f2b-ssh    tcp  --  anywhere             anywhere             multiport dports ssh
DROP       all  --  anywhere             anywhere             match-set blacklist src

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-apache (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-apache-modsecurity (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-apache-noscript (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-apache-overflows (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-asterisk-tcp (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-asterisk-udp (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-nextcloud (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-ssh (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-ssh-ddos (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-vpnserver-tcp (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain f2b-vpnserver-udp (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

PS: currently I haven't installed this script. I used this one instead for now: https://n0where.net/iptables-blacklist-script/
Maybe it's only an old version...

**Comment by jamgregory** [comment]
@jonisc - best practice, at least with the INPUT chain, is to DROP all packets that don't match and only allow in one's you've explicitly allowed. https://support.rackspace.com/how-to/introduction-to-iptables/ is probably a good introduction.

That said, your chain has a rule to explicitly drop everything that matches the blacklist, so it would drop anything in that list anyway.

Hope that helps!

**Comment by jonisc** [comment]
Thank you! I think that helped me to understand better 😉.
