### ISSUE TITLE
ipset v6.23: Error in line 5: Hash is full, cannot add more elements

### ISSUE THREAD

**Issue by PaulGuijt** [trick77/ipset-blacklist#50]
I tried to delete the ipset in order to make a larger one, but that was not allowed:
```
pi@pcg:~ $ sudo ipset destroy blacklists
ipset v6.23: Set cannot be destroyed: it is in use by a kernel component
```
I guess I'm not the only one with this error.

**Comment by trick77** [comment]
It means that it's still referenced in iptables. You have to remove it there first.

**Comment by PaulGuijt** [comment]
You're right. For other users:
- I commented out the rule in my iprules with a '#'
- sudo ipset destroy blacklists ; sudo ipset destroy blacklists-tmp
- sudo nano /etc/ipset-blacklist/ip-blacklist.restore, changing the first two lines into
      create blacklists-tmp -exist hash:net family inet hashsize 32768  maxelem 80000
      create blacklists -exist hash:net family inet hashsize 32768  maxelem 80000
- sudo ipset restore < /etc/ipset-blacklist/ip-blacklist.restore
- removed the '#' in my iprules
- sudo iptables-restore < /etc/iptables/myrules
Finished. I hope ;-)

**Comment by amastelek** [comment]
> 
> 
> You're right. For other users:
> 
>     * I commented out the rule in my iprules with a '#'
> 
>     * sudo ipset destroy blacklists ; sudo ipset destroy blacklists-tmp
> 
>     * sudo nano /etc/ipset-blacklist/ip-blacklist.restore, changing the first two lines into
>       create blacklists-tmp -exist hash:net family inet hashsize 32768  maxelem 80000
>       create blacklists -exist hash:net family inet hashsize 32768  maxelem 80000
> 
>     * sudo /usr/local/sbin/update-blacklist.sh /etc/ipset-blacklist/ipset-blacklist.conf
> 
>     * removed the '#' in my iprules
> 
>     * sudo iptables-restore < /etc/iptables/myrules
> 
> 
> Finished. I hope ;-)

Thanks - I had the same problem.  I think a default of 32768 would be better than 16384 in the script
