### ISSUE TITLE
Error: searching PATH fails to find executables among: curl egrep grep ipset iptables sed sort wc

### ISSUE THREAD

**Issue by enricota66** [trick77/ipset-blacklist#52]
Hi
I get this error: ( I'm sure it's my problem only )
Error: searching PATH fails to find executables among: curl egrep grep ipset iptables sed sort wc.

For easy test I have only one link on my  /etc/ipset-blacklist/ipset-blacklist.conf
"https://www.blocklist.de/downloads/export-ips_all.txt"
The others are all under comment line #.
I don't understand, fallow step by step your guide.
ipset is v6.29 version, but my problem I think is before.

Might I need to root permissions to run the script string "update-blacklist.sh" ?
Thanks a lot.

**Comment by Steve8291** [comment]
What distro are you running? The following may help if you are running Ubuntu.

First check to make sure that each of the executables is installed using the command below.
`whereis curl curl egrep grep ipset iptables sed sort wc`
If any are missing then you should install them like the example:
`apt install wc`

Then you should make sure that the user running the script has those locations as environmental variables for their shell. Run the env command when logged in as the user you want to run the script with.
`env | grep "PATH"`
The paths you found with the whereis command should also be in your PATH.
If you are running from a crontab then you should probably edit the script and add the required paths to the beginning of it like below:
```
#!/bin/bash
PATH=/usr/bin:/sbin:/bin
```

**Comment by enricota66** [comment]
Hi Steve8291
Thanks a lot for your fast reply, you have solve my issue.
My distro is Ubuntu 16.04 LTS desktop.
And I haven't curl package on my system, so I have installed with : 
sudo apt-get install curl
Now the script seems run fine and the files  .list and .restore are created.
So this step is done ... I needed more time to try it.
Thanks again
