### ISSUE TITLE
Blacklist from stopforumspam.com not working

### ISSUE THREAD

**Issue by casperklein** [trick77/ipset-blacklist#54]
fyi: 

Warning: curl returned HTTP response code 404 for URL https://www.stopforumspam.com/downloads/toxic_ip_cidr.txt

**Comment by trick77** [comment]
Thanks, removed.

**Comment by agarzon** [comment]
Not sure if removing the line is a good idea... the TXT version is not available anymore, but that doesn't mean we cannot use their compressed versions. By removing the line means that https://www.stopforumspam.com wont be used anymore, and I strongly believe is a good source of bad ips IMHO.

**Comment by trick77** [comment]
The script doesn't handle zip files and I'm not sure if they're going to enforce some sort of API key in the near future.

**Comment by trick77** [comment]
Re-added stopforumspam via firehol
