### ISSUE TITLE
Small fix to filter out garbage from certain Blacklist URLs

### ISSUE THREAD

**Issue by sbujam** [trick77/ipset-blacklist#74]
Some additional Blacklist URLs (for example  https://myip.ms/browse/blacklist) return blacklisted IPs in the following form:

[...]
177.142.109.24                   # 2018-04-30, b18e6d18.virtua.com.br, BRA, 2
[...]

When this is fed to `grep -Po '(?:\d{1,3}.){3}\d{1,3}(?:/\d{1,2})?'` it returns two lines!
177.142.109.24
2018-04-30

While the first is valid ip, the second is not.

If you change
`command grep -Po '(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?' "$IP_TMP" >> "$IP_BLACKLIST_TMP"'` into
`command grep -Po '^(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?' "$IP_TMP" >> "$IP_BLACKLIST_TMP"'`

the problem is solved :)

**Comment by sbujam** [comment]
And while you're here, please consider my other suggestion to 'fix' invalid IP entries with leading zeros like 012.003.04.05

If you agree, you could change the above line into:
`command grep -Po '^(?:\d{1,3}.){3}\d{1,3}(?:/\d{1,2})?' "$IP_TMP" | sed -r 's/^0*([0-9]+)\.0*([0-9]+)\.0*([0-9]+)\.0*([0-9]+)$/\1.\2.\3.\4/' >> "$IP_BLACKLIST_TMP"`

the last sed discards zeroes in IP addresses

**Comment by trick77** [comment]
Thanks, I just pushed it to the develop branch.
