### ISSUE TITLE
Merge ips into cidrs?

### ISSUE THREAD

**Issue by gilesw** [trick77/ipset-blacklist#76]
Current list comes in at 75k lines

When merged to cidrs 4k lines

Python script example:-

```python
from netaddr import *
import fileinput
import re
iplist = []

for line in fileinput.input():
  ipv4_address = re.compile('(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9]))')
  ipv4 = re.search(ipv4_address, line)

  if ipv4:
    iplist.append(ipv4.group(0))

ip_merge_list=cidr_merge(iplist)
for ip in ip_merge_list:
  print ip
```

**Comment by trick77** [comment]
I know but not everybody has/wants Python on a Linux system. Lookup is not affected anyway, it would only save a bit of memory

**Comment by gilesw** [comment]
Yep I agree. I was only thinking as an option to the script. I might fire a pull over your way.

**Comment by apathyuk** [comment]
is it worth running the list through iprange which optimizes  ip ranges?

ipset list | wc -l
297800

Running it through uprange gives 256236 entries which is ~14% improvement  (and no python required)

**Comment by trick77** [comment]
Support merged to master branch.
