### ISSUE TITLE
upgrade from debian9 to debian10

### ISSUE THREAD

**Issue by wassy83** [trick77/ipset-blacklist#92]
can I safely upgrade my debian9 web server running ipset-blacklist to debian10? I'm a little scared cause NFtables replaced iptables. Maybe there are some steps to take care.
Many thanks

**Comment by vpieper** [comment]
With ```update-alternatives``` you can change to iptables legacy.

https://wiki.debian.org/nftables

**Comment by elico** [comment]
> With `update-alternatives` you can change to iptables legacy.
> 
> https://wiki.debian.org/nftables

@vpieper This repo should be upgraded to support nftables if exists.
There is no real justification to use ipset when nftables has it's own set implementation which is better then iptables+ipset.

@wassy83 It's possible to test this but requires more details about the web server setup you have.
If you can dump iptables rules with `iptables-save` it might help to answer a relevant solution.

**Comment by trick77** [comment]
Since a lot of popular software still relies on iptables (Docker, for instance) there will be no support for nftables from this repo for quite some time. But as always, feel free to post your link to a Bash based nft solution that downloads &  imports large sets of ip addresses.

**Comment by wassy83** [comment]
I updated from debian 9 to 10 without any issue, the script is still working perfectly and I didn't changed anything with update-alternatives, I just changed my repos to buster and upgraded the system. many thanks

**Comment by elico** [comment]
> 
> Since a lot of popular software still relies on iptables (Docker, for instance) there will be no support for nftables from this repo for quite some time. But as always, feel free to post your link to a Bash based nft solution that downloads & imports large sets of ip addresses.

@trick77 These days moving from Debian 9 to Debian 10(buster) doesn't impose any issues related to nftables.
It is a smooth migration.
Also There are ways to work around with Docker and nftables but on Debian 10 you don't have these issues.
